[book]
authors = ["Ankitects Pty Ltd and contributors"]
description = "Ankiに関するよくある質問。Ankiは学習を容易にするプログラムです。"
language = "en"
multilingual = false
src = "src"
title = "Anki よくある質問"

[build]
create-missing = true

[output.html]
no-section-label = true
git-repository-url = "https://github.com/shigeyukey/Anki-faqs-jp/"
additional-css = ["css/misc.css"]

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true
# sites that block programmatic access
exclude = [ 'quora\.com', 'reddit.com', 'superuser.com', 'github.com/open-spaced-repetition' ]
